name: CI
on:
  push:
    tags:
      - "v*"
jobs:
  build-and-push-0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
      - name: Install wasm32-wasi target
        run: rustup target add wasm32-wasi
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
      - name: Run build-and-push script
        run: ./build-and-push.sh
        env:
          OCI_ARTIFACT: thorstenhans/unique-spin-app
          REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          START_AT: 1
          END_AT: 2
  build-and-push-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
      - name: Install wasm32-wasi target
        run: rustup target add wasm32-wasi
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
      - name: Run build-and-push script
        run: ./build-and-push.sh
        env:
          OCI_ARTIFACT: thorstenhans/unique-spin-app
          REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          START_AT: 3
          END_AT: 1000
  build-and-push-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
      - name: Install wasm32-wasi target
        run: rustup target add wasm32-wasi
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
      - name: Run build-and-push script
        run: ./build-and-push.sh
        env:
          OCI_ARTIFACT: thorstenhans/unique-spin-app
          REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          START_AT: 1001
          END_AT: 2000
  build-and-push-3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
      - name: Install wasm32-wasi target
        run: rustup target add wasm32-wasi
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
      - name: Run build-and-push script
        run: ./build-and-push.sh
        env:
          OCI_ARTIFACT: thorstenhans/unique-spin-app
          REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          START_AT: 2001
          END_AT: 3000
  build-and-push-4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
      - name: Install wasm32-wasi target
        run: rustup target add wasm32-wasi
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
      - name: Run build-and-push script
        run: ./build-and-push.sh
        env:
          OCI_ARTIFACT: thorstenhans/unique-spin-app
          REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          START_AT: 3001
          END_AT: 4000
  build-and-push-5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
      - name: Install wasm32-wasi target
        run: rustup target add wasm32-wasi
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
      - name: Run build-and-push script
        run: ./build-and-push.sh
        env:
          OCI_ARTIFACT: thorstenhans/unique-spin-app
          REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          START_AT: 4001
          END_AT: 5000
  update-docker-hub:
    runs-on: ubuntu-latest
    needs: [build-and-push-0]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: thorstenhans/unique-spin-app
          short-description: "5000 unique Spin Apps to demonstrate high-density"
          enable-url-completion: true
