name: CI
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
      - name: Install wasm32-wasi target
        run: rustup target add wasm32-wasi
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
      - name: Run build-and-push script
        run: ./build-and-push.sh
        env:
          OCI_ARTIFACT: thorstenhans/unique-spin-app
          REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: thorstenhans/unique-spin-app
          short-description: "5000 unique Spin Apps to demonstrate high-density"
          enable-url-completion: true
